### ISSUE TITLE
'$make test'  error

### ISSUE THREAD

**Issue by Fourchaux** [rleonid/oml#114]
I'm interested in your test configuration.

On a Linux x86_64 box & OCaml 4.02.3
trying '$make test'  gives :

ocamlbuild -build-dir _driver -I tools joiner.native
Finished, 0 targets (0 cached) in 00:00:00.
Finished, 4 targets (4 cached) in 00:00:00.

ocamlbuild -build-dir _driver -use-ocamlfind -package lacaml -package lbfgs
  -package ocephes -package kaputt -I src/lib/datasets -I src/lib -I src/test driver.test && \
time ./driver.test
Finished, 0 targets (0 cached) in 00:00:00.

ocamlfind ocamldep -package kaputt -package ocephes -package lbfgs -package lacaml
  -pp '~/oml-master/_driver/tools/joiner.native camlp4o' -modules src/lib/util.ml > src/lib/util.ml.depends
Fatal error: exception Sys_error("Invalid cross-device link")

File "src/lib/util.ml", line 1:
Error: Error while running external preprocessor
Command line: ~/oml-master/_driver/tools/joiner.native camlp4o 'src/lib/util.ml' > /tmp/ocamlppa271be
...

Any suggestions ? Thank you.

**Comment by rleonid** [comment]
A bit of googling around led me to [this](http://sourceforge.net/p/ocaml-lib/mailman/message/8325027/). So I suspect that the bug is the unprotected call to [Sys.rename](https://github.com/hammerlab/oml/blob/master/tools/joiner.ml#L106), which is probably because `/tmp` is a different mount on your configuration. I don't have access to a `linux` box at the moment so care to take a stab at fixing this? 

In general the way tests work is that the `joiner` appends the tests in the `.mlp` file to the `.ml` with a little [header](https://github.com/hammerlab/oml/blob/master/tools/joiner.ml#L54) so that it doesn't have to doit over and over again during the build. It is a far from optimal solution.

**Comment by Fourchaux** [comment]
The patch http://sourceforge.net/p/ocaml-lib/mailman/message/8325027/ fixes the pb. 
Thanks for this link.

Now,  $make test -->
File "src/lib/util.ml", line 129, characters 14-24:
Error: Unbound module Rank

Searching ...

**Comment by rleonid** [comment]
[Rank](https://github.com/hammerlab/oml/blob/master/src/lib/rank.ml)... Not certain why it is not found. Is it being correctly copied over, maybe something fishy is going on with the build system. What happens when you do a `ls -R _driver` after a `make test` ?

**Comment by Fourchaux** [comment]
$ ls -R _driver  
_driver:
_digests
_log
myocamlbuild*
myocamlbuild.cmi
myocamlbuild.cmt
myocamlbuild.cmx
myocamlbuild.ml
myocamlbuild.o
ocamlc.where
src/
tools/

_driver/src:
lib/  test/

_driver/src/lib:
classify.cmi
classify.cmti
classify.ml
classify.ml.depends
classify.mli
classify.mli.depends
classify.mlt
continued_fraction.cmi
continued_fraction.cmti
continued_fraction.ml
continued_fraction.ml.depends
continued_fraction.mli
continued_fraction.mli.depends
descriptive.cmi
descriptive.cmti
descriptive.ml
descriptive.ml.depends
descriptive.mli
descriptive.mli.depends
descriptive.mlt
distributions.cmi
distributions.cmti
distributions.ml
distributions.ml.depends
distributions.mli
distributions.mli.depends
distributions.mlt
estimations.cmi
estimations.cmti
estimations.ml
estimations.ml.depends
estimations.mli
estimations.mli.depends
estimations.mlt
functions.cmi
functions.cmti
functions.ml
functions.ml.depends
functions.mli
functions.mli.depends
functions.mlt
inference.cmi
inference.cmti
inference.ml
inference.ml.depends
inference.mli
inference.mli.depends
inference.mlt
interpolate.cmi
interpolate.cmti
interpolate.ml
interpolate.ml.depends
interpolate.mli
interpolate.mli.depends
interpolate.mlt
matrices.cmi
matrices.cmti
matrices.ml
matrices.ml.depends
matrices.mli
matrices.mli.depends
matrices.mlt
measures.cmi
measures.cmti
measures.ml
measures.ml.depends
measures.mli
measures.mli.depends
measures.mlt
oml.mlpack
pca.cmi
pca.cmti
pca.ml
pca.ml.depends
pca.mli
pca.mli.depends
pca.mlt
rank.mlt
regression.cmi
regression.cmti
regression.ml
regression.ml.depends
regression.mli
regression.mli.depends
regression.mlt
running.cmi
running.cmti
running.ml
running.ml.depends
running.mli
running.mli.depends
running.mlt
sampling.cmi
sampling.cmti
sampling.ml
sampling.ml.depends
sampling.mli
sampling.mli.depends
sampling.mlt
solvers.cmi
solvers.cmti
solvers.ml
solvers.ml.depends
solvers.mli
solvers.mli.depends
solvers.mlt
svd.cmi
svd.cmti
svd.ml
svd.ml.depends
svd.mli
svd.mli.depends
svd.mlt
util.annot
util.cmi
util.cmt
util.cmti
util.ml
util.ml.depends
util.mli
util.mli.depends
util.mlt
vectors.cmi
vectors.cmti
vectors.ml
vectors.ml.depends
vectors.mli
vectors.mli.depends
vectors.mlt

_driver/src/test:
driver.ml
driver.ml.depends

_driver/tools:
joiner.annot
joiner.cmi
joiner.cmo
joiner.cmt
joiner.cmx
joiner.ml
joiner.ml.depends
joiner.native*
joiner.o

**Comment by rleonid** [comment]
So it isn't being copied over, hat's confusing. Something must be wrong with the build logic. Can you please email me (see my profile) the contents of `_driver/src/lib/util.ml` and `_driver/src/lib/rank.mlt` after a make test?
Do you experience this problem when you do a regular compile?

**Comment by Fourchaux** [comment]
Here are the 2 files.

I don't know if it's useful but , inside _build/src/lib all the rank files (
rank.cm_/rank.annot/rank.o/rank.ml_) seem correct.

2015-10-16 2:00 GMT+02:00 Leonid Rozenberg notifications@github.com:

**Comment by rleonid** [comment]
Sorry, I didn't get the files. Could you try emailing me directly as opposed to replying to this issue? I suspect that the test `joiner` is perhaps somehow mangling `rank.ml` in compiling the test suite.

**Comment by rleonid** [comment]
They seem to checkout. I don't know what could be causing your error. At this point I'd instrument this [line](https://github.com/hammerlab/oml/blob/master/myocamlbuild.ml#L10) in the `ocamlbuild` plugin, to figure out why `rank.ml` isn't being copied over. It is correctly checked out by `git`, right?

I'll set up a more real time channel (something like gitter) tomorrow, so that I can help you debug it.

**Comment by rleonid** [comment]
@Fourchaux Any updates on your bug?

**Comment by rleonid** [comment]
Closing because I haven't heard back, feel free to re-open if the problem returns @Fourchaux

**Comment by smondet** [comment]
I also hit this one, PR on the way.

**Comment by Fourchaux** [comment]
All tests ... passed.
Gros Gros Merci & Thank you
