### ISSUE TITLE
Power function?  

### ISSUE THREAD

**Issue by struktured** [rleonid/oml#116]
Is there something like a `val pow : base: float -> exp:float -> float` function in oml yet? I didn't see one, but confirming before submitting a pr. I know `exp` exists so that seems like the natural choice for implementing it.

**Comment by rleonid** [comment]
There isn't.

**Comment by rleonid** [comment]
Although off the top of my head I can't think of any, I wonder if there are nuances to implementing a good power function. Specifically, `cephes` seems to have it's own [version](http://www.netlib.org/cephes/doubldoc.html#pow) with this warning

> Following Cody and Waite, this program uses a lookup table
> of 2**-i/16 and pseudo extended precision arithmetic to
> obtain an extra three bits of accuracy in both the logarithm
> and the exponential.

So maybe, depending on how much time you want to spend investigating this issue, exposing that function in [ocephes](https://github.com/rleonid/ocephes) might be the way to go.

**Comment by struktured** [comment]
Took your [advice](https://github.com/rleonid/Ocephes/pull/5), but here's how I did implement it before seeing your comment:

``` Ocaml

let pow ~base x = 
  if not @@ significantly_different_from base 0.0 then 
    0.0
  else
    let sign = if base > 0.0 ||
      int_of_float x mod 2 = 0 then
      1.0
    else
      -1.0
    in
    exp (x *. log (abs_float base)) *. sign
```
