### ISSUE TITLE
Functorize Running interface

### ISSUE THREAD

**Issue by rleonid** [rleonid/oml#127]
`default_mean_value` suppresses some unused argument warnings that are a consequence of bad-design, time to address this. @struktured

**Comment by struktured** [comment]
Ok I'll work on it this week!

**Comment by rleonid** [comment]
Sorry @struktured I beat ya to it, checkout #133. I couldn't get around `ignoring` those extra parameters in the default implementation. We'd have to introduce layers of Functors to overcome this and I'm not certain that is worth while either.

**Comment by struktured** [comment]
I just finished an alternative one, although I haven't documented it yet
and it has a few things I still might want to tweak:

https://github.com/hammerlab/oml/compare/master...struktured:functorize-running?expand=1#diff-75c2f22bf15eaf570b44ced65b028a87R56

In this version, a record of tuple {n_mean;n_var} is returned by the update
function, which avoids the problem you ran into with ignore. If you prefer
your version entirely that's fine, if you want to change the update rule at
least to return a tuple and thereby avoiding your ignore issue, that's
fine. If you want me to modify something for you, that's fine too. You can
also do nothing :)

Cheers,
Carmelo

**Comment by rleonid** [comment]
Pairing it into a record (`{n_mean; n_var}`) is a really good idea, I like it. I'm going to update the [reorg](https://github.com/hammerlab/oml/pull/133)  PR to incorporate it!

Thank you.

**Comment by rleonid** [comment]
Fixed by #133
