### ISSUE TITLE
Polymorphic sampling versions

### ISSUE THREAD

**Issue by struktured** [rleonid/oml#15]
In the mood to implement sooner rather than later a `Sampling.Poly` module. However, how would one implement this succinctly? 

Do I write an equivalent version of each function that exists in `Sampling` manually, or do I make a functor which is then used by both the "primitive" and polymorphic version?

Open to any thoughts on the matter, or if you want to wait before making any changes this drastic yet.

**Comment by rleonid** [comment]
Go for it!

I think that some kind of Functor version will ultimately be the result, and we can instantiate that functor in `Sampling` "primitive" if we want to keep the interface simple. But there's no harm in putting down working code (without interface if desired) to see what the corner cases look like.

**Comment by struktured** [comment]
Done in #18.
