### ISSUE TITLE
make setup fails

### ISSUE THREAD

**Issue by ihodes** [rleonid/oml#158]
```
~/workspace/oml > make setup
opam install lacaml lbfgs ocephes kaputt dsfo bisect_ppx
[ERROR] No package named dsfo found.
make: *** [setup] Error 66
```

opam pinning https://github.com/rleonid/dsfo worked to get around this (though, horribly, reinstalled every single ocaml library on my computer; thank you aspcud?)

**Comment by rleonid** [comment]
I don't think you should realistically blame `dsfo|oml` for relying on `ocamlfind` and consequently triggering a rebuild of all your tools. Remember, you can say `no` to opam.

**Comment by ihodes** [comment]
No blame is lain at the feet of dsfo/oml! Except that dsfo cannot be opam installed and thus `make setup` fails.
