### ISSUE TITLE
Stochastic Gradient Descent

### ISSUE THREAD

**Issue by struktured** [rleonid/oml#16]
Is there a preferred ocaml library for this already? Is it worth implementing for oml? Have a colleague who is considering writing a pure ocaml version of this algorithm.

**Comment by rleonid** [comment]
I know that [Olearn](https://github.com/hammer/olearn/blob/master/src/lib/olearn.ml) has one, and Jeff mentioned that [GPR](https://github.com/mmottl/gpr) also has an implementation. But I haven't taken the time to evaluate these options, so your colleagues opinions are welcome!

**Comment by struktured** [comment]
Will try to find another algorithm that doesn't already have two implementations in ocaml then!
