### ISSUE TITLE
Matrix Determinant

### ISSUE THREAD

**Issue by jparsert** [rleonid/oml#176]
I did not see any determinant function. Any objection to my adding one?

**Comment by rleonid** [comment]
Yes, there is no determinant function in the `Matrix` module and a pure `OCaml` contribution is warmly welcome.

But if you're looking to get something working now, there is a driver over `lacaml` in the [determinant_symmetric](https://github.com/hammerlab/oml/blob/master/src/lib/unc/lacaml_util.ml#L211) and more general [determinant](https://github.com/hammerlab/oml/blob/master/src/lib/unc/lacaml_util.ml#L263) method in the [Lacaml_util.ml](https://github.com/hammerlab/oml/blob/master/src/lib/unc/lacaml_util.ml) module.

**Comment by rleonid** [comment]
@fourtytwo I'm curious, what did you end up using? What is your use case?

**Comment by jparsert** [comment]
@rleonid  I used the one you pointed to... but i intend to write a pure ocaml version once i have more time.
