### ISSUE TITLE
Beta and Dirichlet Distributions

### ISSUE THREAD

**Issue by struktured** [rleonid/oml#19]
This is a must have for me at this point, especially sampling functions. @rleonid do you have any existing code for this before I get started?

**Comment by struktured** [comment]
@rleonid I noticed you already defined the beta function, so the majority of the work is already done for the beta distribution. Sweet!

**Comment by rleonid** [comment]
Yes, I started implementing those functions because I wanted to compare and sample from different distributions. I don't think I have other functions that I haven't implemented.

**Comment by rleonid** [comment]
At least the Dirichlet pdf is now present by #123.
