### ISSUE TITLE
no random forests?

### ISSUE THREAD

**Issue by UnixJunkie** [rleonid/oml#190]

**Comment by rleonid** [comment]
Sadly not yet, with the usual contributions welcome caveat. You might be interested in @mmottl's [aifad](https://github.com/mmottl/aifad).

**Comment by mmottl** [comment]
Though AIFAD isn't a random forest approach in the classical sense, some flags allow you to use randomness for classification tree generation to avoid myopic solutions found by purely greedy heuristics.  This can lead to trees that compress the data better.  One could conceivably combine several random classification trees to form an ensemble.

Another tree-based OCaml algorithm (gradient-boosted trees) can be found here: https://github.com/alexbaretta/dawg

**Comment by UnixJunkie** [comment]
I have added oc45 and orandforest to opam very recently.
Thanks to @mmottl for the interesting pointers.
