### ISSUE TITLE
Failed to build with lacaml 9.2.3

### ISSUE THREAD

**Issue by wangjiezhe** [rleonid/oml#191]
I think it's due to mmottl/lacaml@f99d4211c91f8f0ab88aab858657f48f3e3d495f

**Comment by rleonid** [comment]
Thanks for reporting. I've add a [PR](https://github.com/hammerlab/oml/pull/192) that fixes the build. I'll added the necessary constraints to [opam repository](https://github.com/ocaml/opam-repository/pull/8727).
