### ISSUE TITLE
Are you interested by some functions:

### ISSUE THREAD

**Issue by UnixJunkie** [rleonid/oml#193]
Classification:
- AUC
- power metric
- early enrichment at given cutoff
Distances/scores:
- Tanimoto score and distance
- Tversky score

**Comment by rleonid** [comment]
Of course! I'd be happy to have all contributions.
Though for the record, there I did take some pains to implement `AUC` well [here](https://github.com/hammerlab/oml/blob/master/src/cls/oml_performance.ml#L73).

**Comment by UnixJunkie** [comment]
I have released them separately in the cpm library in opam.

**Comment by rleonid** [comment]
That's great, you've been doing admirable work in single handedly implementing a lot of good ML functionality.
