### ISSUE TITLE
Library purpose and intentions 

### ISSUE THREAD

**Issue by struktured** [rleonid/oml#7]
Would you describe this project as a light weight pure ocaml alternative to gsl and pareto? When should a user consider using this math library (based on your vision of the project)? If I were to start using it, are you taking PR requests?

Finally, is an opam release on the horizon?

Thanks

**Comment by rleonid** [comment]
> Would you describe this project as a light weight pure ocaml alternative to gsl and pareto?

That's a fair description.

I've accumulated a fair bit of `F#`, `OCaml` and `Haskell` code that I've written over the years that does this stuff in a pure manner  (well except for the dropping down to BLAS-LAPACK for the linear algebra). I'm working in `OCaml` right now and want to be to perform regressions and tests easily, so I decided to put this up. I've uploaded about 40% of what I've transcribed. But once I finish that, I want to put in a bit of work towards documenting and testing before I release it to opam and take PR's.

**Comment by rleonid** [comment]
I have some idea's for how to implement things like data frames or exploring statistical properties using higher order types, that I would like to try out. I'm not certain if this library will be the place for that or a different repository.

**Comment by struktured** [comment]
Ok thanks for the clarifications, I'll watch this project for further updates!
